import {
  facebook,
  linkedin,
  instagram,
  twitter,
  github,
  facebook1,
  linkedin1,
  instagram1,
  twitter1,
  github1,
  guesstheword,
  carrental,
  guesstheword1,
  guesstheword2,
  guesstheword3,
  carrental1,
  carrental2,
  carrental3,
  responsive,
  react,
  fullstack,
  chipotle,
  chipotle1,
  chipotle2,
  chipotle3,
  ChefMade,
  ChefMade1,
  ChefMade2,
  ChefMade3,
  AIBioBooster,
  AIBioBooster1,
  AIBioBooster2,
  AIBioBooster3,
  AIBioBooster4,
  CookInMyHome,
  CookInMyHome1,
  CookInMyHome2,
  CookInMyHome3,
  Menutiger,
  Menutiger1,
  Menutiger2,
  Menutiger3,
  walkerfurniture,
  walkerfurniture1,
  walkerfurniture2,
  walkerfurniture3,
  Fearrininsurance,
  Fearrininsurance1,
  Fearrininsurance2,
  Fearrininsurance3,
  GoAuto,
  GoAuto1,
  GoAuto2,
  GoAuto3,
  Tutorful,
  Tutorful1,
  Tutorful2,
  Tutorful3,
  FbaTool,
  FbaTool1,
  FbaTool2,
  FbaTool3,
  recipeapp,
  recipeapp3,
  recipeapp4,
  recipeapp6,
  healththefood,
  healththefood1,
  healththefood2,
  healththefood3,
  healththefood4,
  commectthecommstruction,
  commectthecommstruction1,
  commectthecommstruction2,
  commectthecommstruction3,
  commectthecommstruction4,
} from "../assets";

const social = [
  {
    id: 1,
    name: "LinkedIn",
    url: "https://",
    icon: linkedin,
    icon1: linkedin1,
  },
  {
    id: 2,
    name: "Facebook",
    url: "https://",
    icon: facebook,
    icon1: facebook1,
  },
  {
    id: 3,
    name: "Instagram",
    url: "https://",
    icon: instagram,
    icon1: instagram1,
  },
  {
    id: 4,
    name: "Twitter",
    url: "https://",
    icon: twitter,
    icon1: twitter1,
  },
  {
    id: 5,
    name: "Github",
    url: "https://github.com/midas3110-git",
    icon: github,
    icon1: github1,
  },
];

const technologies = [
  {
    stack: ["languages", "all"],
    name: "HTML 5",
    icon: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/html5/html5-plain.svg",
  },
  {
    stack: ["languages", "all"],
    name: "CSS 3",
    icon: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/css3/css3-plain.svg",
  },
  {
    stack: ["languages", "all"],
    name: "JavaScript",
    icon: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/javascript/javascript-plain.svg",
  },
  {
    stack: ["languages", "all"],
    name: "C#",
    icon: "src/assets/icons/Cs.png",
  },
  {
    stack: ["languages", "all"],
    name: "Java",
    icon: "src/assets/icons/java.png",
  },
  {
    stack: ["languages", "all"],
    name: "Ruby",
    icon: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/ruby/ruby-plain.svg",
  },
  {
    stack: ["languages", "all"],
    name: "Python",
    icon: "https://img.icons8.com/?size=100&id=13441&format=png&color=000000",
  },
  {
    stack: ["languages", "all"],
    name: "PHP",
    icon: "https://www.svgrepo.com/show/303656/php-logo.svg",
  },
  {
    stack: ["frameworks", "all"],
    name: "Vue",
    icon: "https://upload.wikimedia.org/wikipedia/commons/9/95/Vue.js_Logo_2.svg",
  },
  {
    stack: ["frameworks", "all"],
    name: "React JS",
    icon: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/react/react-original.svg",
  },
  {
    stack: ["frameworks", "all"],
    name: "Laravel",
    icon: "https://upload.wikimedia.org/wikipedia/commons/9/9a/Laravel.svg",
  },
  {
    stack: ["languages", "all"],
    name: "Django",
    icon: "src/assets/icons/django.png",
  },
  {
    stack: ["frameworks", "all"],
    name: "Ruby on Rails",
    icon: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/rails/rails-plain.svg",
  },
  {
    stack: ["frameworks", "all"],
    name: "Redux Toolkit",
    icon: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/redux/redux-original.svg",
  },
  {
    stack: ["frameworks", "all"],
    name: "Bootstrap",
    icon: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/bootstrap/bootstrap-plain.svg",
  },
  {
    stack: ["frameworks", "all"],
    name: "Tailwind CSS",
    icon: "https://img.icons8.com/?size=100&id=CIAZz2CYc6Kc&format=png&color=000000",
  },
  {
    stack: ["frameworks", "all"],
    name: "Jest",
    icon: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/jest/jest-plain.svg",
  },
  {
    stack: ["frameworks", "all"],
    name: "RSpec",
    icon: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/rspec/rspec-original.svg",
  },
  {
    stack: ["tools", "all"],
    name: "MySQL",
    icon: "https://upload.wikimedia.org/wikipedia/ru/thumb/6/62/MySQL.svg/2560px-MySQL.svg.png",
  },
  // {
  //   stack: ['tools', 'all'],
  //   name: 'AWS',
  //   icon: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR2xQcwKitRgXfqdi34DYlocPSEXD2G2zZipg&s',
  // },
  {
    stack: ["tools", "all"],
    name: "MongoDB",
    icon: "https://cdn.worldvectorlogo.com/logos/mongodb-icon-2.svg",
  },
  {
    stack: ["tools", "all"],
    name: "PostgreSQL",
    icon: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/postgresql/postgresql-plain.svg",
  },
  {
    stack: ["tools", "all"],
    name: "Figma",
    icon: "https://www.vectorlogo.zone/logos/figma/figma-icon.svg",
  },
  {
    stack: ["tools", "all"],
    name: "Framer",
    icon: "src/assets/icons/framer.png",
  },
  {
    stack: ["tools", "all"],
    name: "Make",
    icon: "src/assets/icons/make.png",
  },
  {
    stack: ["tools", "all"],
    name: "Postman",
    icon: "https://www.vectorlogo.zone/logos/getpostman/getpostman-icon.svg",
  },
  {
    stack: ["tools", "all"],
    name: "Git",
    icon: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/git/git-plain.svg",
  },
  {
    stack: ["tools", "all"],
    name: "GitHub",
    icon: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/github/github-original.svg",
  },
  {
    stack: ["tools", "all"],
    name: "Docker",
    icon: "https://img.icons8.com/?size=100&id=cdYUlRaag9G9&format=png&color=000000",
  },
];

const projects = [
  {
    id: 1,
    name: "CHIPOTLE HONEY CHICKEN",
    desc: "I supported data layer integration with Adobe Client Data Layer for structured tracking and personalization. On the backend, I worked with Java-based services to deliver scalable and secure APIs. The site’s UX was enhanced with PWA support, Lottie animations, and accessibility features via UsableNet.",
    tech: ["Java", "Open Graph", "PWA"],
    img: chipotle,
    carousel: [chipotle1, chipotle2, chipotle3],
    source_link: "hhttps://github.com/john1123-git/Car-Rental-front-end",
    live_link: "https://www.chipotle.com/",
  },
  {
    id: 2,
    name: "Fearrininsurance",
    desc: "I developed features for the Fearrin Insurance website using Microsoft ASP.NET, enhancing both functionality and security with integrations like reCAPTCHA and HSTS. I implemented interactive UI elements using jQuery and FancyBox and optimized the user experience with Google Fonts and embedded Google Maps. I also configured Google Analytics, Google Tag Manager, and DoubleClick Floodlight for tracking and marketing attribution, while leveraging Google-hosted libraries for efficient asset delivery.",
    tech: ["ASP.NET", "RSS", "JQuery"],
    img: Fearrininsurance,
    carousel: [Fearrininsurance1, Fearrininsurance2, Fearrininsurance3],
    source_link: "hhttps://github.com/john1123-git/Car-Rental-front-end",
    live_link: "https://www.fearrininsurance.com/",
  },
  {
    id: 3,
    name: "walkerfurniture",
    desc: "I developed a responsive and visually appealing e-commerce platform using HTML, CSS, and JavaScript, with Microsoft ASP.NET powering the backend. I implemented key features such as product listings, secure payment processing, and performance optimization. To boost traffic and usability, I integrated Elasticsearch for search functionality and SEO enhancements, creating a smooth and customer-focused shopping experience.",
    tech: ["ASP.NET", "AIpine.js", "Open Graph"],
    img: walkerfurniture,
    carousel: [walkerfurniture1, walkerfurniture2, walkerfurniture3],
    source_link: "hhttps://github.com/john1123-git/Car-Rental-front-end",
    live_link: "https://www.walkersfurniture.com/",
  },
  {
    id: 4,
    name: "CookInMyHome",
    desc: "I developed a responsive and visually appealing e-commerce platform using HTML, CSS, and JavaScript, with Microsoft ASP.NET powering the backend. I implemented key features such as product listings, secure payment processing, and performance optimization. To boost traffic and usability, I integrated Elasticsearch for search functionality and SEO enhancements, creating a smooth and customer-focused shopping experience.",
    tech: ["Vue.js", "JQuery", "Open Graph", "Popper"],
    img: CookInMyHome,
    carousel: [CookInMyHome1, CookInMyHome2, CookInMyHome3],
    source_link: "hhttps://github.com/john1123-git/Car-Rental-front-end",
    live_link: "https://cookinmyhome.com/",
  },
  {
    id: 5,
    name: "Tutorful",
    desc: "I contributed to Tutorful, an education platform connecting students with tutors, by developing performant and accessible front-end interfaces using Vue.js, Nuxt.js, and Bootstrap 5. I integrated dynamic animations with GSAP and optimized the UI using lit-html and Lodash. The platform is powered by a PHP backend and uses Storyblok as a headless CMS. I implemented Google Sign-In for secure user authentication and configured analytics tools including GA4, Amplitude, and Datadog. Additional enhancements included Trustpilot integration for social proof, OptiMonk for marketing automation, and Cloudflare Turnstile for bot protection.",
    tech: ["Vue.js", "Nuxt.js", "Webpack"],
    img: Tutorful,
    carousel: [Tutorful1, Tutorful2, Tutorful3],
    source_link: "hhttps://github.com/john1123-git/Car-Rental-front-end",
    live_link: "https://tutorful.co.uk/",
  },
  {
    id: 6,
    name: "MenuTiger",
    desc: "I contributed to MenuTiger, a QR-based digital menu platform for restaurants, by building responsive interfaces and server-rendered pages using React and Next.js. I implemented secure user interactions with reCAPTCHA, integrated Google Analytics and Tag Manager for performance tracking, and supported ad attribution through DoubleClick Floodlight. Asset bundling and performance optimizations were handled with Webpack, ensuring fast load times and seamless user experience across devices.",
    tech: ["React", "Next.js", "Webpack"],
    img: Menutiger,
    carousel: [Menutiger1, Menutiger2, Menutiger3, CookInMyHome],
    source_link: "hhttps://github.com/john1123-git/Car-Rental-front-end",
    live_link: "https://www.menutiger.com/",
  },
  {
    id: 7,
    name: "GoAuto",
    desc: "I contributed to GoAuto, a large-scale automotive sales platform, by developing high-performance user interfaces using Preact, Next.js, and Tailwind CSS. I supported real-time feature delivery via Webpack and implemented robust backend interactions through Yii and PHP. My responsibilities also included optimizing the platform’s SEO with Open Graph metadata, integrating Apple Sign-In for secure authentication, and enhancing reliability by monitoring errors using Sentry. The platform is deployed on AWS for scalability and speed.",
    tech: ["React", "Next.js", "Webpack", "Open Garph", "Tailwind CSS"],
    img: GoAuto,
    carousel: [GoAuto1, GoAuto2, GoAuto3],
    source_link: "hhttps://github.com/john1123-git/Car-Rental-front-end",
    live_link: "https://www.goauto.ca/",
  },
  {
    id: 8,
    name: "ChefMade",
    desc: "I helped build Chefmade, a Danish chef-for-hire platform, by developing modern front-end interfaces using React, Alpine.js, and Preact, with interactive functionality supported by htmx and JSS. On the backend, I integrated Django to manage user flows and content. I implemented PWA capabilities for mobile optimization, secured the app with HSTS, and enhanced SEO/social sharing through Open Graph and Google Fonts. I also integrated Google Tag Manager and ad services (Google Ads, DoubleClick Floodlight) for marketing and analytics. The platform runs on DigitalOcean Spaces for scalable asset storage.",
    tech: ["React", "Django", "Open Garph", "PWA"],
    img: ChefMade,
    carousel: [ChefMade1, ChefMade2, ChefMade3],
    source_link: "hhttps://github.com/john1123-git/Car-Rental-front-end",
    live_link: "https://www.goauto.ca/",
  },
  {
    id: 9,
    name: "AI Bio Booster",
    desc: "I developed the AI Bio Booster platform using Framer and React, creating a responsive and interactive UI with Framer Motion and Lenis for smooth animations. On the backend, I built automated AI-driven workflows using Make.com, combining OpenAI APIs (ChatGPT, DALL·E, Whisper), Webhooks, and JSON processing. Additional infrastructure included Stripe for billing, AWS and Amazon S3 for hosting, and analytics/tracking via Google Analytics, Tag Manager, and LinkedIn Ads. I ensured compliance and security with HSTS, OneTrust, and Cloudflare Bot Management.",
    tech: ["React", "TypeScript", "Figma", "Framer", "Make"],
    img: AIBioBooster,
    carousel: [AIBioBooster1, AIBioBooster2, AIBioBooster3, AIBioBooster4],
    source_link: "hhttps://github.com/john1123-git/Car-Rental-front-end",
    live_link: "https://aibio.framer.website/",
  },
  {
    id: 10,
    name: "Amazon FBA Box Content Tool",
    desc: "I used React to provide a user-friendly and intuitive interface with effectiv file input/output stream. I also enabled uploading, downloading, and editing of Excel files on web browser easily.",
    tech: ["React", "PWA"],
    img: FbaTool,
    carousel: [FbaTool1, FbaTool2, FbaTool3],
    source_link: "hhttps://github.com/john1123-git/Car-Rental-front-end",
    live_link: "https://freelancer-001.web.app/",
  },
  {
    id: 11,
    name: "Car Rental App",
    desc: "The Car Rental App is a comprehensive full-stack application where you can seamlessly explore an array of cars, search by name, delve into comprehensive car details, make reservations when logged in, manage reservations, add or delete cars in the database, and personalize your profile with ease.",
    tech: ["React", "Redux", "Ruby on Rails", "PostgreSQL"],
    img: carrental,
    carousel: [carrental1, carrental2, carrental3],
    source_link: "hhttps://github.com/john1123-git/Car-Rental-front-end",
    live_link: "https://car-rental121.netlify.app/",
  },
  {
    id: 12,
    name: "Recipe App",
    desc: "The Recipe app keeps track of all your foods, recipes, and ingredients. It allows you to save ingredients, keep track of what you have, create recipes, and generate a shopping list based on what you have and what you are missing from a recipe. Since sharing recipes is an important part, it allows you to make them public so anyone can access them.",
    tech: ["Ruby", "Ruby on Rails", "PostgreSQL"],
    img: recipeapp,
    carousel: [recipeapp3, recipeapp4, recipeapp6],
    source_link: "https://github.com/john1123-git/Recipe-App",
    live_link: "https://recipe-app121-b8888e20687b.herokuapp.com/",
  },
  {
    id: 13,
    name: "Guess the word",
    desc: "Guess The Word is a fun letter puzzle game where the player have to guess the hidden word using the clues that the game gives. The game ends if the player guesses the correct word or if he chooses the wrong letter 8 times. Mainly built with Javascript.",
    tech: ["HTML5", "CSS3", "JavaScript"],
    img: guesstheword,
    carousel: [guesstheword1, guesstheword2, guesstheword3],
    source_link: "https://github.com/john1123-git/Guess-the-word",
    live_link: "https://guess-the-word121.netlify.app/",
  },
  {
    id: 14,
    name: "Healthy the food",
    desc: "HealthyFood.com is a wellness and nutrition website offering expert-backed recipes, meal plans, and health advice tailored to various dietary needs. It aims to make healthy living easy and enjoyable through practical tips, product reviews, and science-based guidance. Mainly built with PHP(wordpress).",
    tech: ["PHP(Wordpress)", "CSS3", "JavaScript"],
    img: healththefood,
    carousel: [healththefood1, healththefood2, healththefood3, healththefood4],
    source_link: "https://github.com/john1123-git/Guess-the-word",
    live_link: "https://healthyfood.com/",
  },
  {
    id: 15,
    name: "Commect the construction",
    desc: "​CommectConstruction.com is the online presence of Commect Construction, a company specializing in construction and infrastructure development projects. The website provides information about their services, project portfolio, and contact details for potential clients and partners. Mainly built with Laravel.",
    tech: ["PHP(Laravel)", "CSS3", "JavaScript"],
    img: commectthecommstruction,
    carousel: [
      commectthecommstruction1,
      commectthecommstruction2,
      commectthecommstruction3,
      commectthecommstruction4,
    ],
    source_link: "https://github.com/john1123-git/Guess-the-word",
    live_link: "https://connectconstruction.com/",
  },
];

// const testimonials = [
//   {
//     id: 1,
//     name: 'Ahmed Hasan Rony',
//     image: 'https://avatars.githubusercontent.com/u/77187003?v=4',
//     text: 'I really am comfortable with collaborating and coding with Barry. His ingenious ideas give me a lot of ideas solving a problem multiple ways.',
//     country: 'India',
//     linkedIn: 'https://www.linkedin.com/in/ahroniy/',
//   },
//   {
//     id: 2,
//     name: 'Rachel Isaac',
//     image: 'https://media.licdn.com/dms/image/D4D35AQHOKsZ2nSaTjg/profile-framedphoto-shrink_400_400/0/1665541124692?e=1721469600&v=beta&t=Evk76YZRsti88Lyr1khjrlxcZKF8v2hrbA3G7YLhIz4',
//     text: "Throughout our collaboration, I was consistently impressed by Barry's professionalism, attention to detail, and ability to adapt to changing requirements.",
//     country: 'United Arab Emirates',
//     linkedIn: 'https://www.linkedin.com/in/racheleno/',
//   },
//   {
//     id: 3,
//     name: 'Muhammad Talha Hanif',
//     image: 'https://media.licdn.com/dms/image/D4D03AQF6A-cET7akGQ/profile-displayphoto-shrink_400_400/0/1687861230806?e=1726099200&v=beta&t=C1jrASsQ8AXgmkVrndSBMyBfh7eTBQ_pe2VG79FSNN0',
//     text: 'He possesses a deep understanding of the latest technologies and trends in his field, allowing him to tackle complex challenges with ease.',
//     country: 'Pakistan',
//     linkedIn: 'https://www.linkedin.com/in/muhammad-talha-hanif/',
//   },
//   {
//     id: 4,
//     name: 'Jerome Osman',
//     image: 'https://media.licdn.com/dms/image/D4D03AQE1F2tqE5cttw/profile-displayphoto-shrink_400_400/0/1694205105262?e=1726099200&v=beta&t=TYftRu2dWsY-5eUgZSsorbbURiQMGtGVOcmcJeDrsGQ',
//     text: 'His kindness and patience with his peers makes him easy to work with no matter the difficulty, and that reflects as well when it comes to helping others in his team or explaining something when need be',
//     country: 'South Africa',
//     linkedIn: 'https://www.linkedin.com/in/jerome-osman/',
//   },
//   {
//     id: 5,
//     name: 'Innocent N.',
//     image: 'https://media.licdn.com/dms/image/D5603AQE1qYMUswBOAw/profile-displayphoto-shrink_400_400/0/1688151359384?e=1726099200&v=beta&t=rkHvuiSC9ww8BOxUhz2cqpIdzAoW6ZUEWbJDQW5W5OU',
//     text: 'Communication was another strength that Barry brought to the table. He actively listened, communicated ideas clearly, and collaborated effectively with team members.',
//     country: 'Rwanda',
//     linkedIn: 'https://www.linkedin.com/in/innocent-n/',
//   },
//   {
//     id: 6,
//     name: 'Marko Kermichiev',
//     image: 'https://avatars.githubusercontent.com/u/112749658?v=4',
//     text: 'I learned too much from you and I can say that you are fantastic developer. Working with you is always a pleasure, hope that we can work on some project asap.',
//     country: 'Macedonia',
//     linkedIn: 'https://www.linkedin.com/in/marko-kermichiev/',
//   },
// ];

const services = [
  {
    id: 1,
    icon: responsive,
    title: "Responsive Design",
    text: "I specialize in creating websites that are not just visually stunning but also highly adaptable. My responsive designs ensure that your site looks and works perfectly on any device, providing an exceptional user experience regardless of screen size.",
  },
  {
    id: 2,
    icon: react,
    title: "Front-end Development",
    text: "I breathe life into your creative ideas by translating them into captivating web interfaces. Using the latest frontend technologies and best practices, I build engaging, user-friendly websites that leave a lasting impression.",
  },
  {
    id: 3,
    icon: fullstack,
    title: "Back-end Development",
    text: "My backend development expertise forms the backbone of your web application. I design and build robust, efficient, and secure server-side solutions that handle data management and business logic seamlessly, ensuring your website functions flawlessly.",
  },
];

const navLinks = [
  {
    id: 1,
    name: "About",
    url: "/#about",
  },
  {
    id: 2,
    name: "Service",
    url: "/#service",
  },
  {
    id: 3,
    name: "Work",
    url: "/#work",
  },
  // {
  //   id: 4,
  //   name: 'Testimonial',
  //   url: '/#testimonial',
  // },
  {
    id: 5,
    name: "Contact",
    url: "/#contact",
  },
];

export {
  technologies,
  projects,
  social,
  services,
  navLinks,
  // testimonials,
};
